#define BBKEY_TARGET TEXT("Target")
#define BBKEY_HOMEPOS TEXT("HomePos")
#define BBKEY_PATROLPOS TEXT("PatrolPos")
#define BBKEY_ISHIT TEXT("bIsHit")
#define BBKEY_ISMOVING TEXT("bIsMoving")
#define BBKEY_ISFIRSTCONTACT TEXT("bIsFirstContact")
#define BBKEY_BOSSPATTERN TEXT("BossPattern")
#define BBKEY_BOSSPASE TEXT("BossPase")
