#define BBKEY_TARGET TEXT("Target")
#define BBKEY_HOMEPOS TEXT("HomePos")
#define BBKEY_PATROLPOS TEXT("PatrolPos")
#define BBKEY_ISHIT TEXT("bIsHit")
#define BBKEY_ISFIRSTCONTACT TEXT("bIsFirstContact")